apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  capacity:
    storage: 125Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: storage-account
    shareName: persistentvolumecreate
    readOnly: false
  persistentVolumeReclaimPolicy: Retain